// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RosBilRP.Models;

[Table("Opgave")]
public partial class Opgave
{
    [Key]
    public int Id { get; set; }

    public int AnsatId { get; set; }

    public int LejeId { get; set; }

    [Required]
    [StringLength(50)]
    public string Beskrivelse { get; set; }

    public bool Afsluttet { get; set; }

    [ForeignKey("AnsatId")]
    [InverseProperty("Opgaves")]
    public virtual Ansat Ansat { get; set; }

    [ForeignKey("LejeId")]
    [InverseProperty("Opgaves")]
    public virtual Leje Leje { get; set; }
}