// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace RosBilRP.Models;

public partial class RosBilDBContext : DbContext
{
    public RosBilDBContext()
    {
    }

    public RosBilDBContext(DbContextOptions<RosBilDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Ansat> Ansats { get; set; }

    public virtual DbSet<Bil> Bils { get; set; }

    public virtual DbSet<Kunde> Kundes { get; set; }

    public virtual DbSet<Leje> Lejes { get; set; }

    public virtual DbSet<Opgave> Opgaves { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer("Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=RosBilDB;Integrated Security=True;Encrypt=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Ansat>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Ansat__3214EC078ACFC5D6");

            entity.Property(e => e.Id).ValueGeneratedNever();
        });

        modelBuilder.Entity<Bil>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Bil__3214EC0728FCD03E");

            entity.Property(e => e.Id).ValueGeneratedNever();
        });

        modelBuilder.Entity<Kunde>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Kunde__3214EC0761F43992");

            entity.Property(e => e.Id).ValueGeneratedNever();
        });

        modelBuilder.Entity<Leje>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Leje__3214EC07D81AE975");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasOne(d => d.Bil).WithMany(p => p.Lejes)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BilId");

            entity.HasOne(d => d.Kunde).WithMany(p => p.Lejes)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_KundeId");
        });

        modelBuilder.Entity<Opgave>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Opgave__3214EC07919354EF");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasOne(d => d.Ansat).WithMany(p => p.Opgaves)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AnsatId");

            entity.HasOne(d => d.Leje).WithMany(p => p.Opgaves)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_LejeId");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__User__3214EC07F81EA17F");

            entity.Property(e => e.Id).ValueGeneratedNever();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}