// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RosBilRP.Models;

[Table("Kunde")]
public partial class Kunde
{
    [Key]
    public int Id { get; set; }

    [Required(ErrorMessage = "Du skal angive et navn")]
    [StringLength(50)]
    public string Navn { get; set; }

    public int Telefon { get; set; }

    [Column("VIP")]
    public bool Vip { get; set; }

    [InverseProperty("Kunde")]
    public virtual ICollection<Leje> Lejes { get; set; } = new List<Leje>();


}