// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RosBilRP.Models;

[Table("Bil")]
public partial class Bil : IHarId
{
    [NotMapped]
    public int Id
    {
        get { return BilId; }
        set { BilId = value; }
    }

    [Key]
    public int BilId { get; set; }

    [Required]
    [StringLength(50)]
    public string Nummerplade { get; set; }

    [Required]
    [StringLength(50)]
    public string Model { get; set; }

    public int PrisPrDag { get; set; }

    [InverseProperty("Bil")]
    public virtual ICollection<Leje> Lejes { get; set; } = new List<Leje>();
}