// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace RosBilRP.Models;

public partial class RosBilDBContext : DbContext
{
    public RosBilDBContext()
    {
    }

    public RosBilDBContext(DbContextOptions<RosBilDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Bil> Bils { get; set; }

    public virtual DbSet<Kunde> Kundes { get; set; }

    public virtual DbSet<Leje> Lejes { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer("Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=RosBilDB;Integrated Security=True;Encrypt=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Bil>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Bil__3214EC07CD0C67D9");

            entity.Property(e => e.Id).ValueGeneratedNever();
        });

        modelBuilder.Entity<Kunde>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Kunde__3214EC0797752410");

            entity.Property(e => e.Id).ValueGeneratedNever();
        });

        modelBuilder.Entity<Leje>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Leje__3214EC07C682517C");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasOne(d => d.Bil).WithMany(p => p.Lejes)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BilId");

            entity.HasOne(d => d.Kunde).WithMany(p => p.Lejes)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_KundeId");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__User__3214EC07EBC4A7CA");

            entity.Property(e => e.Id).ValueGeneratedNever();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}